### ISSUE TITLE
MaxPool

### ISSUE THREAD

**Issue by franalgaba** [gizatechxyz/orion#126]
# Feature Request

**Describe the Feature Request**

Implementation of ONNX Operator

**Describe Preferred Solution**

Implementation following the same Operator interface as defined in ONNX. See [Contribution Guidelines](https://orion.gizatech.xyz/community/contribute#add-a-new-feature)

**Additional Context**

[ONNX MaxPool Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#MaxPool)

**Comment by Roee-87** [comment]
I'll take this one

**Comment by berwingan** [comment]
@raphaelDkhn  hey if no one is working on this, can i ?

**Comment by raphaelDkhn** [comment]
Hi, is this RP in progress?

**Comment by berwingan** [comment]
Hey, I did not make progress on this and have unassigned myself.

**Comment by chachaleo** [comment]
Can I take it ? :)
