### ISSUE TITLE
OneHot

### ISSUE THREAD

**Issue by franalgaba** [gizatechxyz/orion#127]
# Feature Request

**Describe the Feature Request**

Implementation of ONNX Operator

**Describe Preferred Solution**

Implementation following the same Operator interface as defined in ONNX. See [Contribution Guidelines](https://orion.gizatech.xyz/community/contribute#add-a-new-feature)

**Additional Context**

[ONNX OneHot Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#OneHot)

**Comment by hakymulla** [comment]
i'll take this one

**Comment by raphaelDkhn** [comment]
#187
