### ISSUE TITLE
QLinearMatMul

### ISSUE THREAD

**Issue by franalgaba** [gizatechxyz/orion#129]
# Feature Request

**Describe the Feature Request**

Implementation of ONNX Operator

**Describe Preferred Solution**

Implementation following the same Operator interface as defined in ONNX. See [Contribution Guidelines](https://orion.gizatech.xyz/community/contribute#add-a-new-feature)

**Additional Context**

[ONNX QLinearMatMul Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearMatMul)

**Comment by chachaleo** [comment]
Can I take it ?

**Comment by chachaleo** [comment]
Hey, I have a question : in the example in the documentation of onnx ([ONNX QLinearMatMul Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearMatMul))

the scale et zero point have different types : 
```python
a_scale = np.array([0.0066], dtype=np.float32)
a_zero_point = np.array([113], dtype=np.uint8)
```
the function `dequantize_linear` as currrently implemented doesn't support different types for scale et zero point :`quantize_linear( x: @Tensor<Q>, x_scale: @Tensor<T>, x_zero_point: @Tensor<T>)` (same issue for `quantize_linear`)

Do I make a version of QlinearMatMul limited that only support the cases supported by `dequantize_linear` and `quantize_linear`  or should I modify these two functions to support more general cases ?

**Comment by raphaelDkhn** [comment]
> Hey, I have a question : in the example in the documentation of onnx ([ONNX QLinearMatMul Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearMatMul))
> 
> the scale et zero point have different types :
> 
> ```python
> a_scale = np.array([0.0066], dtype=np.float32)
> a_zero_point = np.array([113], dtype=np.uint8)
> ```
> 
> the function `dequantize_linear` as currrently implemented doesn't support different types for scale et zero point :`quantize_linear( x: @Tensor<Q>, x_scale: @Tensor<T>, x_zero_point: @Tensor<T>)` (same issue for `quantize_linear`)
> 
> Do I make a version of QlinearMatMul limited that only support the cases supported by `dequantize_linear` and `quantize_linear` or should I modify these two functions to support more general cases ?

If you use two types, you risk having to make conversions, and having compatibility errors in Cairo. I think it's better in our case to use just one type.
