### ISSUE TITLE
Conv

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#178]
[Conv](https://github.com/onnx/onnx/blob/main/docs/Operators.md#conv)

**Comment by Falco90** [comment]
Can I take this issue?

**Comment by raphaelDkhn** [comment]
@Falco90 sorry I missed that comment, are you still in working on it?

**Comment by namn-grg** [comment]
@raphaelDkhn if no one is working on this, I can take this up.

**Comment by chachaleo** [comment]
Hello! Can I take this ?
