### ISSUE TITLE
Example on how to convert weights and biases to Cairo

### ISSUE THREAD

**Issue by franalgaba** [gizatechxyz/orion#19]

**Comment by Xaxxoo** [comment]
Hi @franalgaba Could you please explain what is needed to be done here?

**Comment by raphaelDkhn** [comment]
Hi @Xaxxoo, this issue is outdated as it's now managed by [Giza Transpiler](https://cli.gizatech.xyz/frameworks/cairo/transpile). 

I'll close this issue
