### ISSUE TITLE
Feat: QLinearAveragePool

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#314]
Implement [QLinearAveragePool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearAveragePool) operator.

**Comment by HappyTomatoo** [comment]
@raphaelDkhn I can't find this operator in the ONNX library

**Comment by raphaelDkhn** [comment]
@HappyTomatoo Thanks, it means it's deprecated. I'll close that issue
