### ISSUE TITLE
Feat: Compress

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#315]
Implement [Compress](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Compress) operator.

**Comment by hakymulla** [comment]
I'll take this one

**Comment by hakymulla** [comment]
> I'll take this one

😏

**Comment by raphaelDkhn** [comment]
> > I'll take this one
> 
> 😏

Oups sorry, missed it
