### ISSUE TITLE
Feat: OptionalHasElement

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#321]
Implement [OptionalHasElement](https://github.com/onnx/onnx/blob/main/docs/Operators.md#OptionalHasElement) operator.

**Comment by HappyTomatoo** [comment]
@raphaelDkhn You can assign it to me.

**Comment by HappyTomatoo** [comment]
I noticed that there is an operator called [`optional_get_element`](https://github.com/gizatechxyz/orion/blob/3cfa61067d24215a828d27e8c6a208ca3a43ec1b/src/operators/tensor/math/optional_get_element.cairo#L9) implemented in `src.operator.tensor.math`. However, I also noticed that [ONNX](https://onnx.ai/onnx/operators/onnx__OptionalHasElement.html) requires support for types including both `sequences` and `tensors`. So, I would like to know if `optional_has_element` should be implemented separately in `src.operator.sequence` and `src.operator.tensor`, and additionally, `optional_get_element` should be implemented specifically in `src.operator.sequence`.
