### ISSUE TITLE
Feat: QLinearSigmoid

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#337]
Implement [QLinearSigmoid](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearSigmoid) operator.

**Comment by 0x73e** [comment]
I couldn't find this operator along with some of the other QLinear ones in the link. Is there an updated version somewhere?

**Comment by raphaelDkhn** [comment]
Hmm you are right it has been deprecated. I will close that issue. Thanks!
