### ISSUE TITLE
Feat: Scatter

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#341]
Implement [Scatter](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Scatter) operator.

**Comment by hakymulla** [comment]
According to the ONNX repo
Scatter (deprecated)
This operator is deprecated. Please use ScatterElements, which provides the same functionality.

**Comment by raphaelDkhn** [comment]
Thanks @hakymulla, I'll close this one
