### ISSUE TITLE
Feat: Erf

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#349]
Implement [Erf](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Erf) operator.

**Comment by 0x73e** [comment]
I can take this one

**Comment by 0x73e** [comment]
@raphaelDkhn Took a stab at implementing this. However, think that the method is quite unstable for small values (tried to use https://personal.math.ubc.ca/~cbm/aands/page_299.htm 7.1.26

Can let someone else work on this if possible and I'll work on a more widely used operator instead.

**Comment by raphaelDkhn** [comment]
Sure @0x73e

**Comment by raphaelDkhn** [comment]
I would suggest to first implement `erf` lookup table in Fixed Point library. In order to implement `erf` operator element-wise

**Comment by HappyTomatoo** [comment]
Hey Raphael! I'll take this one.
