### ISSUE TITLE
Feat: QLinearMatMul

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#352]
Implement [QLinearMatMul](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QLinearMatMul) operator.

**Comment by chachaleo** [comment]
Can I continue working on this ? (#129)

**Comment by raphaelDkhn** [comment]
Sure @chachaleo! Sorry that's a duplicate issue. I will close this one. But ofc you can still continue on this. The implementation is assigned to you :)
