### ISSUE TITLE
dev: unnecessary reverse in broadcast_shape

### ISSUE THREAD

**Issue by chachaleo** [gizatechxyz/orion#393]
In the implementation of `broadcast_shape` in https://github.com/gizatechxyz/orion/blob/main/src/operators/tensor/helpers.cairo

The array is popped backward and then reversed. 

It is done so that in case the length of the two shape array don't match, 1 is appended at the end of the short one. However, the first line of the code is `check_compatibility`, which assert that the length are the same, which make this procedure unnecessary.

**Related Code**

```rust
fn broadcast_shape(mut shape1: Span<usize>, mut shape2: Span<usize>) -> Span<usize> {
    check_compatibility(shape1, shape2);
    let mut result: Array<usize> = ArrayTrait::new();

    loop {
        let mut dim1 = 1;
        let mut dim2 = 1;

        match shape1.pop_back() {
            Option::Some(item) => {
                dim1 = *item;
            },
            Option::None(_) => {
                if shape1.len() == 0 && shape2.len() == 0 {
                    break ();
                };
            }
        };

        match shape2.pop_back() {
            Option::Some(item) => {
                dim2 = *item;
            },
            Option::None(_) => {
                if shape1.len() == 0 && shape2.len() == 0 {
                    break ();
                };
            }
        };

        let broadcasted_dim = u32_max(dim1, dim2);
        result.append(broadcasted_dim);
    };

    return result.reverse().span();
}
```

**What is the new behavior?**

`pop_front` and not reversing would be cheaper.

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes

**Comment by raphaelDkhn** [comment]
You are right, thanks @chachaleo! Feel free to open a PR :)
