### ISSUE TITLE
dev: optimizing transpose

### ISSUE THREAD

**Issue by chachaleo** [gizatechxyz/orion#394]
In the implementation of `tensor.transpose` in https://github.com/gizatechxyz/orion/blob/main/src/operators/tensor/linalg/transpose.cairo

The implementation is very general and support any permutations. However, one of the most general use case, matrix transposition, could be done in a more optimized way. As it is used a lot in matrix theory and in linear algebra it can be important to have a more optimized implementation.

**What is the new behavior?**
Either calling the current implementation `tensor.permutation` and making an optimized transpose function only for 2D tensors  (without having to specify the axis permutation [1,0]). 
Or keeping it this way but having a check if the dimension is 2 and calling a sub-function (maybe `transpose_2D`), with a more optimized implementation

**Optimization**

The current implementation creates for each element some arrays to support the very general n dimensions permutation problem, it uses some effort and computation to retrieve each elements is the input array. In 2 dimension this is trivial and a much cheaper implementation can be done

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes

**Comment by raphaelDkhn** [comment]
I agree with you! I'd prefer the option of checking if the dimension is 2 and calling a sub-function with a more optimized implementation. In general, this is what I think should be done for any function optimization. It will simplify transpilation (ONNX -> OrionCairo)
