### ISSUE TITLE
feat: complex numbers

### ISSUE THREAD

**Issue by chachaleo** [gizatechxyz/orion#464]
# Feature Request

**Describe the Feature Request**

Complex numbers implementation and related mathematics methods.

I will follow a similar structure as fixed point and signed integer and create the `ComplexTrait` and also implement the traits needed (Into, Add, AddEq,  Sub, ... ) for the implementation complex64

**Describe Preferred Solution**

```rust
struct complex64 {
    real: FP64x64,
    img: FP64x64
}
```

**Additional Context**
Needed to implement Issue #290

**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No

**Comment by raphaelDkhn** [comment]
Amazing!
