### ISSUE TITLE
feat: Linear Classifier

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#507]
[Here's](https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#aionnxmllinearclassifier) the operator description.

[Here](https://github.com/onnx/onnx/blob/main/onnx/reference/ops/aionnxml/op_linear_classifier.py) is the onnx python implementation.

**Comment by chachaleo** [comment]
Can I take it ? :)
