### ISSUE TITLE
dev: Refactor Loops in Orion

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#572]
With the integration of Cairo 2.5.x into Orion, it's an opportune moment to enhance our loop structures. Here's a guideline for the refactoring process:

- Prioritize the adoption of while loops as detailed in the [Cairo Book](https://book.cairo-lang.org/ch02-05-control-flow.html?highlight=while%20loop#conditional-loops-with-while).
- In cases where while loops are not suitable, ensure that array iterations conform to best practices for clarity and performance, as outlined in the guide on [idiomatic array looping](https://cairopractice.com/posts/idiomatic-array-looping/).

**Comment by TAdev0** [comment]
hi @raphaelDkhn , may i work on this issue?

**Comment by TAdev0** [comment]
@raphaelDkhn  i'm also refactoring other stuff : 
- panic! macro now available instead of panic
- array! macro for instantiating and filling arrays in a single line
- homogeneity in some files : for ex , a few functions in tensor helpers use ` return x;`, and other `x ` for the return value, i make it consistent

tell me if this is ok for you :)

**Comment by raphaelDkhn** [comment]
Perfect Thank you :) 
Cairo has changed a lot since Orion's first commits. An refactoring is definitely in order! Thanks!

**Comment by TAdev0** [comment]
@raphaelDkhn  just some news : 

I noticed using macros is not really gas efficient, for example : 

```
#[cfg(test)]
// 101270
#[test]
#[should_panic]
fn test_panic_macro_gas() {
    panic!("The input is an empyt optional-type.")
}

// 800 
#[test]
#[should_panic]
fn test_panic_function_gas() {
    panic(array!['The input is an empty', 'optional-type.'])
}
```
or for assert : 

```
#[cfg(test)]
// 9970
#[test]
fn test_assert_macro_gas() {
    assert!(1 == 1, "");
}

// 990 
#[test]
fn test_assert_function_gas() {
    assert(1 == 1, '');
}
```

I think you might to keep functions instead of macros for gas efficiency?

**Comment by raphaelDkhn** [comment]
> @raphaelDkhn  just some news : 
> 
> 
> 
> I noticed using macros is not really gas efficient, for example : 
> 
> 
> 
> ```
> 
> #[cfg(test)]
> 
> // 101270
> 
> #[test]
> 
> #[should_panic]
> 
> fn test_panic_macro_gas() {
> 
>     panic!("The input is an empyt optional-type.")
> 
> }
> 
> 
> 
> // 800 
> 
> #[test]
> 
> #[should_panic]
> 
> fn test_panic_function_gas() {
> 
>     panic(array!['The input is an empty', 'optional-type.'])
> 
> }
> 
> ```
> 
> or for assert : 
> 
> 
> 
> ```
> 
> #[cfg(test)]
> 
> // 9970
> 
> #[test]
> 
> fn test_assert_macro_gas() {
> 
>     assert!(1 == 1, "");
> 
> }
> 
> 
> 
> // 900 
> 
> #[test]
> 
> fn test_assert_function_gas() {
> 
>     assert(1 == 1, '');
> 
> }
> 
> ```
> 
> 
> 
> Maybe  you might want to keep functions instead of macros for gas efficiency?
> 
> For assert, consumption is small in both cases, but the returned string will cost way more with the macro (but anyway, if the assertion fails, the programm will stop so it is not a big deal)
> 
> 
> 
> 

Wow that's great! Thanks @TAdev0! Yes we can replace with functions if it improves performance efficiency

**Comment by TAdev0** [comment]
Same applies for panic : 

```
#[cfg(test)]
// 101270
#[test]
#[should_panic]
fn test_panic_macro_gas() {
    panic!("The input is an empyt optional-type.")
}

// 800 
#[test]
#[should_panic]
fn test_panic_function_gas() {
    panic(array!['The input is an empty', 'optional-type.'])
}
```

panic! macro is more convenient, but less efficient, will stick to panic function everywhere !
