### ISSUE TITLE
dev: TreeEnsembleClassifier and TreeEnsembleRegressor are deprecated in ONNX. Replace them with the TreeEnsemble operator.

### ISSUE THREAD

**Issue by DanielUH2019** [gizatechxyz/orion#575]
Hi, I noticed this task mentioned on https://blog.onlydust.com/blog/odhack-1st-edition/. Is this still available? If so, may I take on this task?

**Comment by raphaelDkhn** [comment]
Yes! Sorry I forgot to open the issue

**Comment by DanielUH2019** [comment]
Ok, I'll start working on that then

**Comment by raphaelDkhn** [comment]
> Ok, I'll start working on that then 

Thanks!

You have the documentation of the operator here:
https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#ai.onnx.ml.TreeEnsemble

And it’s implementation in python here:
https://github.com/onnx/onnx/blob/main/onnx/reference/ops/aionnxml/op_tree_ensemble.py

**Comment by DanielUH2019** [comment]
Hey @raphaelDkhn, I'm seeking guidance on how to tackle a specific section of code within the Python implementation. I'm unsure about the following portion:  
```python  
class Node:
    compare: Callable[[float, float | set[float]], bool]
    true_branch: Node | Leaf
    false_branch: Node | Leaf
    feature: int

    def __init__(
        self,
        mode: Mode,
        value: float | set[float],
        feature: int,
        missing_tracks_true: bool,
```                                                                                                                                                                         
In this snippet, the value parameter can either be a single float or a set of floats. In cairo I could do something like:
enum NodeValue<T> {
    Value: T,
    MemberValue: Felt252Dict<T>
}   
but T is not hashable, is this approach correct?

**Comment by raphaelDkhn** [comment]
> Hey @raphaelDkhn, I'm seeking guidance on how to tackle a specific section of code within the Python implementation. I'm unsure about the following portion:
> 
> ```python
> class Node:
>     compare: Callable[[float, float | set[float]], bool]
>     true_branch: Node | Leaf
>     false_branch: Node | Leaf
>     feature: int
> 
>     def __init__(
>         self,
>         mode: Mode,
>         value: float | set[float],
>         feature: int,
>         missing_tracks_true: bool,
> ```
> 
> In this snippet, the value parameter can either be a single float or a set of floats. In cairo I could do something like:
> 
> ```
> enum NodeValue<T> {
>     Value: T,
>     MemberValue: Felt252Dict<T>
> }   
> ```
> 
> but T is not hashable, is this approach correct?

You can use [Nullable Dictionaries](https://book.cairo-lang.org/ch03-02-dictionaries.html#dictionaries-of-types-not-supported-natively) for types not natively supported. However, is the dictionary necessary? Can't we use `Span` instead? The more we can avoid dictionaries, the better. Because in Cairo, dictionaries have a worst-case time complexity of O(n) for both writing and reading!

**Comment by DanielUH2019** [comment]
I'm uncertain about the purpose of using a set in the Python implementation. Is its primary function simply to facilitate easy membership checking, as shown in this code snippet?
```python
elif mode == Mode.MEMBER:
           self.compare = lambda x: x[feature].item() in value or (
                missing_tracks_true and np.isnan(x[feature].item())
            )
```
Or does it also serve to prevent duplicate values?
```python
if nodes_modes[current_node_index] == Mode.MEMBER:
                # parse next sequence of set members
                set_members = set()
                while (set_member := next(set_membership_iter)) and not np.isnan(
                    set_member
                ):
                    set_members.add(set_member)
```
If it's guaranteed that values are never repeated then the dictionary wouldn't be necessary

**Comment by raphaelDkhn** [comment]
Hi @DanielUH2019, how is this PR going? Let me know if you need any help or have any questions.

**Comment by chachaleo** [comment]
I'll work on this :)
