### ISSUE TITLE
Update Orion's ReduceSum Operator to Align with Latest ONNX Interface Changes

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#583]
The latest ONNX release introduces modifications to the ReduceSum operator. To align with these changes, it's necessary to update our implementation of the ReduceSum operator in Orion, ensuring compatibility with the new interface. 

For reference, details about the updated operator can be found here: [ONNX ReduceSum Documentation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#reducesum).

**Comment by FriendlyLifeguard** [comment]
Can I take this?

**Comment by raphaelDkhn** [comment]
Hi @FriendlyLifeguard, if you don't mind, I'll take care of this issue after all as it's a blocking issue in Giza that we need to make progress with to implement other operators that depends on it. If you've already implemented it, please let me know.

**Comment by FriendlyLifeguard** [comment]
That ok with me! I will tackle other issues. I will comment on them once I get the chance.

**Comment by raphaelDkhn** [comment]
https://github.com/gizatechxyz/orion/pull/608
