### ISSUE TITLE
feat: Acos

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#85]
# Feature Request

**Describe the Feature Request**

Calculates the arccosine (inverse of cosine) of the given input tensor, element-wise.

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#acos

**Comment by hakymulla** [comment]
can i work on this?

**Comment by raphaelDkhn** [comment]
https://github.com/gizatechxyz/orion/pull/161
