### ISSUE TITLE
feat: Acosh

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#86]
# Feature Request

**Describe the Feature Request**

Calculates the hyperbolic arccosine of the given input tensor element-wise.

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#acosh

**Comment by Roee-87** [comment]
completed

**Comment by raphaelDkhn** [comment]
https://github.com/gizatechxyz/orion/pull/137
