### ISSUE TITLE
feat: ArgMin

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#87]
# Feature Request

**Describe the Feature Request**

Computes the indices of the min elements of the input tensor's element along the provided axis. The resulting tensor has the same rank as the input if keepdims equals 1. If keepdims equals 0, then the resulting tensor has the reduced dimension pruned. If select_last_index is True (default False), the index of the last occurrence of the min is selected if the min appears more than once in the input. Otherwise the index of the first occurrence is selected. The type of the output tensor is integer.

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#ArgMin

**Comment by credence0x** [comment]
can this be assigned to me?
