### ISSUE TITLE
feat: Compress

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#93]
# Feature Request

**Describe the Feature Request**

Selects slices from an input tensor along a given axis where condition evaluates to True for each axis index. In case axis is not provided, input is flattened before elements are selected. Compress behaves like numpy.compress: https://docs.scipy.org/doc/numpy/reference/generated/numpy.compress.html

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Compress

**Comment by credence0x** [comment]
Hello. I'd like to have this assigned to me
