### ISSUE TITLE
feat: Cosh

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#96]
# Feature Request

**Describe the Feature Request**

Calculates the hyperbolic cosine of the given input tensor element-wise.

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cosh

**Comment by Roee-87** [comment]
I can take assignment on this one.

**Comment by Roee-87** [comment]
completed

**Comment by raphaelDkhn** [comment]
https://github.com/gizatechxyz/orion/pull/132
