### ISSUE TITLE
feat: LogSoftmax

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#99]
# Feature Request

**Describe the Feature Request**

The operator computes the log of softmax values for the given input.

Full description here: https://github.com/onnx/onnx/blob/main/docs/Operators.md#logsoftmax

**Comment by Roee-87** [comment]
I'll take assignment on this one

**Comment by raphaelDkhn** [comment]
https://github.com/gizatechxyz/orion/pull/105
